function internal_log_bs_timing(props, mode)
% INTERNAL_LOG_BS_TIMING Append timing metadata to a central CSV log.
%   internal_log_bs_timing(props, mode)
%   mode: 'compute_bs' or 'compute_bs_ap'
%
% This helper is intentionally lightweight and silent on failure.
%
% Columns:
%   timestamp, git_commit, case_id, mode, parallel, samples, reltol, abstol,
%   elapsed, ap_total, ap_iters, ap_each_vector
%
% The ap_* columns are populated only for mode='compute_bs_ap'.
%
% To identify case studies, ensure your setup_* script sets
%   props.meta.case_id   (string)   OR we fallback to props.model.name if present.
%
% Log file: bs_timing_log.csv in current working directory.
%
% NOTE: This is automatically invoked inside compute_bs and compute_bs_ap.
%
% (Autogenerated helper)

try
    if ~isfield(props,'profiling'); return; end

    ts = '';
    if isfield(props.profiling,'bs_timestamp'); ts = props.profiling.bs_timestamp; else; ts = datestr(now,'yyyy-mm-ddTHH:MM:SS'); end
    gitc = '';
    if isfield(props.profiling,'git_commit'); gitc = props.profiling.git_commit; end

    case_id = '';
    if isfield(props,'meta') && isfield(props.meta,'case_id'); case_id = props.meta.case_id; end
    if isempty(case_id) && isfield(props,'model') && isfield(props.model,'name'); case_id = props.model.name; end
    if isempty(case_id); case_id = 'unknown_case'; end

    parallel_flag = ''; if isfield(props,'flagParallel'); parallel_flag = num2str(props.flagParallel); end
    samples = ''; if isfield(props,'profiling') && isfield(props.profiling,'bs_num_samples'); samples = num2str(props.profiling.bs_num_samples); end

    reltol = ''; abstol = '';
    if isfield(props,'ti') && isfield(props.ti,'options')
        if isfield(props.ti.options,'RelTol'); reltol = num2str(props.ti.options.RelTol); end
        if isfield(props.ti.options,'AbsTol'); abstol = num2str(props.ti.options.AbsTol); end
    end

    elapsed = '';
    if strcmp(mode,'compute_bs') && isfield(props.profiling,'bs_last_elapsed')
        elapsed = num2str(props.profiling.bs_last_elapsed);
    elseif strcmp(mode,'compute_bs_ap') && isfield(props.profiling,'bs_ap_total')
        elapsed = num2str(props.profiling.bs_ap_total);
    end

    ap_total = ''; ap_iters = ''; ap_each_vector = '';
    if strcmp(mode,'compute_bs_ap')
        if isfield(props.profiling,'bs_ap_total'); ap_total = num2str(props.profiling.bs_ap_total); end
        if isfield(props.profiling,'bs_ap_iters'); ap_iters = num2str(props.profiling.bs_ap_iters); end
        if isfield(props.profiling,'bs_ap_each')
            vec = props.profiling.bs_ap_each;
            ap_each_vector = ['[', strjoin(string(vec.'),' '), ']'];
        end
    end

    header = {'timestamp','git_commit','case_id','mode','parallel','samples','RelTol','AbsTol','elapsed','ap_total','ap_iters','ap_each'};
    row = {ts, gitc, case_id, mode, parallel_flag, samples, reltol, abstol, elapsed, ap_total, ap_iters, ap_each_vector};

    logfile = 'bs_timing_log.csv';
    need_header = exist(logfile,'file')~=2;
    fid = fopen(logfile,'a');
    if fid==-1; return; end
    if need_header
        fprintf(fid,'%s\n', strjoin(header,','));
    end
    fprintf(fid,'%s\n', strjoin(row,','));
    fclose(fid);
catch
    % silent failure to avoid disrupting scientific runs
end
end
